In [37]:
import numpy as np

# 1- Arange Followed by reshape

In [2]:
def arange_reshape(x,a,b):
    oneD = []
    twoD = []
    midD = []
    for i in range(x):
        oneD.append(i)
    l = 0
    j = 0
    k = 0
    while k < a:
        while j < b :
            midD.append(oneD[l])
            l+= 1
            j+= 1
        k+= 1
        j = 0
        twoD.append(midD)
        midD = []
    return np.array(twoD)
            
        

In [3]:
arange_reshape(15, 3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 2- Ravel

In [4]:
arr = np.array([[1, 3, 11],[2, 0, 14],[17, 0, 1]])
arr

array([[ 1,  3, 11],
       [ 2,  0, 14],
       [17,  0,  1]])

In [41]:
def ravel(arr):
    oneD = []
    for rows in arr:
        for elements in rows:
            oneD.append(elements)
    return oneD

In [42]:
ravel(arr)

[1, 3, 11, 2, 0, 14, 17, 0, 1]

# 3- Finding MAX in an array

In [6]:
def max(arr):
    oneD = ravel(arr)
    maximum = oneD[1]
    i = 1
    for i in oneD:
        if i > maximum:
            maximum = i
    return maximum
        

In [7]:
max(arr)

17

# 4- Finding MIN in an array

In [8]:
def min(arr):
    oneD = ravel(arr)
    minimum = oneD[1]
    i=1
    for i in oneD:
        if i < minimum:
            minimum = i 
    return minimum
        

In [9]:
min(arr)

0

# 5- Finding argMAX in an array

In [10]:
def argmax(arr):
    maximum = max(arr)
    oneD = ravel(arr)
    for i in range(len(oneD)):
        if oneD[i] == maximum:
            return i
        

In [11]:
argmax(arr)

6

In [12]:
np.argmax(arr)

6

# 6- Finding argMIN in an arry

In [13]:
def argmin(arr):
    minimum = min(arr)
    oneD = ravel(arr)
    for i in range(len(oneD)):
        if oneD[i] == minimum:
            return i
      

In [14]:
argmin(arr)

4

# 7- Sum

In [15]:
def sum(arr):
    oneD = ravel(arr)
    sum = 0
    for i in oneD:
        sum+=i
    return sum
        

In [16]:
sum(arr)

49

# 8- Mean

In [17]:
def mean(arr):
    oneD = ravel(arr)
    sum = 0
    len = 0
    for i in oneD:
        sum+=i
        len+=1
    return float(sum/len)

In [18]:
mean(arr)

5.444444444444445

In [19]:
np.mean(arr)

5.4444444444444446

# 9- Find Shape

In [20]:
def shape(arr):
    r = 0
    c = 0
    for rows in arr:
        r+=1
        c = 0
        for columns in rows:
            c+=1
    return r, c

# 10- Diag

In [21]:
def diag(arr):
    r, c = shape(arr)
    diagonal = []
    for i in range(r):
       for j in range(c):
            if(i == j):
                diagonal.append(arr[i][j])
    return diagonal

In [22]:
diag(arr)

[1, 0, 1]

# 11- Flatten

In [23]:
def flatten(arr, order = 'C'):
    if order == 'C':
        return ravel(arr)
    if order == 'F':
        oneD = []
        r, c= shape(arr)
        for columns in range(c):
            for rows in range(r):
               oneD.append(arr[rows][columns])
        return oneD

# 12- Identity/Eye

In [24]:
def eye(arr):
    r, c = shape(arr)
    for i in range(r):
        for j in range(c):
            if (i == j):
                arr[i][j] = 1
            else:
                arr[i][j] = 0
    return arr

In [25]:
eye(kk)

NameError: name 'kk' is not defined

# 13- Triu

In [ ]:
arr = np.array([[1,3,11],[2,0,14],[17,0,1]])
arr

In [ ]:
def triu(arr):
    r, c = shape(arr)
    for i in range(r):
        for j in range(c):
            if j < i:
                arr[i][j] = 0
    return arr
triu(arr)

# 14- Tril

In [ ]:
arr = np.array([[1,3,11],[2,0,14],[17,0,1]])
arr

In [ ]:
def tril(arr):
    r, c = shape(arr)
    for i in range(r):
        for j in range(c):
            if j > i:
                arr[i][j] = 0
    return arr
tril(arr)

# 16- Element Wise Multiplication

In [ ]:
A = arange_reshape(6, 2, 3)
B = arange_reshape(6, 2, 3)
def element_wise_mul(A, B):
    ra, ca = shape(A)
    rb, cb = shape(B)
    if ra == rb and ca == cb:    
        C = np.zeros(ra*ca).reshape(ra, ca)
        for i in range (ra):
            for j in range (ca):
                C[i][j] = A[i][j] * B[i][j]
        return C
    else :
        return 'Wrong Size'

A * B == element_wise_mul(A, B)

# 17- Dot Product

In [35]:
A = arange_reshape(6, 2, 3)
B = arange_reshape(6, 3, 2)
def dot(A,B):
    ra, ca = shape(A)
    rb, cb = shape(B)
    if ca == rb :    
        C = np.zeros(ra*cb).reshape(ra, cb)
        for i in range (ra):
            for j in range (cb):
                for k in range (ca):
                    C[i][j]+= A[i][k] * B[k][j]
        print (C)
dot(A,B)

[[ 10.  13.]
 [ 28.  40.]]


In [36]:
np.dot(A,B)

array([[10, 13],
       [28, 40]])