In [1]:
import numpy as np

In [2]:
n =  np.random.rand( 3,5)

In [3]:
n

array([[ 0.98647789,  0.29583032,  0.1507959 ,  0.63864984,  0.3436508 ],
       [ 0.6136167 ,  0.7391391 ,  0.88414788,  0.97820186,  0.12292332],
       [ 0.6308301 ,  0.28469314,  0.16072651,  0.0272048 ,  0.24817885]])

# 1- np.min()

In [4]:
n.min()

0.027204802503062231

In [5]:
n.min( axis = 0)

array([ 0.6136167 ,  0.28469314,  0.1507959 ,  0.0272048 ,  0.12292332])

In [6]:
n.min( axis = 1)

array([ 0.1507959 ,  0.12292332,  0.0272048 ])

# 2- np.max()

In [7]:
n.max()

0.98647789232738681

In [8]:
n.max( axis = 0)

array([ 0.98647789,  0.7391391 ,  0.88414788,  0.97820186,  0.3436508 ])

In [9]:
n.max( axis = 1)

array([ 0.98647789,  0.97820186,  0.6308301 ])

# 3- np.sum()

In [10]:
n.sum()

7.1050670037750159

# 4- Dot Product

In [11]:
A = np.random.randn( 5,3)
B = np.random.rand( 3,6)

In [12]:
np.dot( A,B)

array([[ 0.10581109, -0.11790226, -0.23728925,  0.10210505, -0.18740589,
        -0.04731863],
       [ 0.12576951,  0.89104955,  1.30566611,  0.30464423,  0.83991506,
         0.60077588],
       [-0.73218266,  0.35074693,  0.7125858 ,  0.600999  ,  0.44922483,
         0.57653241],
       [-0.76618983, -0.67457927, -0.68746939, -0.66835188, -0.30871738,
        -0.49669291],
       [-0.43861038,  0.16085166,  0.51316616, -0.70563916,  0.49831925,
        -0.10069162]])

# 5- Element Multiplication

In [13]:
a = np.array([[ 1,2],
   [ 3,4]])

In [14]:
b = np.array([[ 5,6],
   [ 7,8]])

In [15]:
a * b

array([[ 5, 12],
       [21, 32]])

# 6- Arange and Reshape

In [16]:
nn = np.arange( 15).reshape( 3,5)
nn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 7- np.argmax()

In [17]:
np.argmax( nn)

14

In [18]:
np.argmax( nn, axis = 0)

array([2, 2, 2, 2, 2])

In [19]:
np.argmax( nn, axis = 1)

array([4, 4, 4])

# 8- np.argmin()

In [20]:
np.argmin( nn)

0

In [21]:
np.argmin( nn, axis = 0)

array([0, 0, 0, 0, 0])

In [22]:
np.argmin( nn, axis = 1)

array([0, 0, 0])

# 9- np.mean()

In [23]:
np.mean(n)==np.average(n)

True

# 10- np.diag()

In [24]:
nn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
np.diag(nn)

array([ 0,  6, 12])

In [26]:
np.diag(nn,k=1)

array([ 1,  7, 13])

In [27]:
np.diag(nn,k=-1)

array([ 5, 11])

# 11- np.ravel()

In [28]:
np.ravel(nn)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 12- np.flatten()

In [29]:
nn.flatten("F")

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

# 13- np.triu()

In [30]:
nd=np.arange(9).reshape((3,3))
nd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.triu(nd)

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

# 14- np.tril()

In [32]:
np.tril(nd)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

# 15- np.eye()

In [33]:
kk=np.eye(3)
kk

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# 16- np.linalg.solve()

In [34]:
a=np.array([[3,4],[5,8]])
b=np.array([6,7])

In [35]:
np.linalg.solve(a,b)

array([ 5.  , -2.25])